%geteyemetrics eye_indices_12c.log wole.log
%geteyemetrics eye_indices_12b.log wole.log
geteyemetrics eye_indices_12a.log wole.log
%geteyemetrics eye_indices_11c.log wole.log
geteyemetrics eye_indices_11b.log wole.log
geteyemetrics eye_indices_11a.log wole.log
geteyemetrics eye_indices_10c.log wole.log
geteyemetrics eye_indices_10b.log wole.log
%geteyemetrics eye_indices_10a.log wole.log
geteyemetrics eye_indices_09c.log wole.log
geteyemetrics eye_indices_09b.log wole.log
%geteyemetrics eye_indices_09a.log wole.log
%geteyemetrics eye_indices_14c.log wole.log
geteyemetrics eye_indices_14b.log wole.log
geteyemetrics eye_indices_13a.log wole.log
%geteyemetrics eye_indices_13b.log wole.log
geteyemetrics eye_indices_13c.log wole.log
geteyemetrics eye_indices_02a.log wole.log
geteyemetrics eye_indices_02b.log wole.log
%geteyemetrics eye_indices_02c.log wole.log
%geteyemetrics eye_indices_03a.log wole.log
geteyemetrics eye_indices_03b.log wole.log
%geteyemetrics eye_indices_03c.log wole.log
%geteyemetrics eye_indices_04a.log wole.log
geteyemetrics eye_indices_04b.log wole.log
geteyemetrics eye_indices_04c.log wole.log
geteyemetrics eye_indices_05a.log wole.log
geteyemetrics eye_indices_05b.log wole.log
%geteyemetrics eye_indices_05c.log wole.log
geteyemetrics eye_indices_06a.log wole.log
%geteyemetrics eye_indices_06b.log wole.log
geteyemetrics eye_indices_06c.log wole.log
geteyemetrics eye_indices_07a.log wole.log
%geteyemetrics eye_indices_07b.log wole.log
geteyemetrics eye_indices_07c.log wole.log
geteyemetrics eye_indices_14a.log wole.log
