matchlog ucl_client_12c.log ../spec_logs/sfd_client_spec_12c.log ../spec_logs/sfd_client_spec_modified_12c.log
matchlog ucl_client_12b.log ../spec_logs/sfd_client_spec_12b.log ../spec_logs/sfd_client_spec_modified_12b.log
matchlog ucl_client_12a.log ../spec_logs/sfd_client_spec_12a.log ../spec_logs/sfd_client_spec_modified_12a.log
matchlog ucl_client_11c.log ../spec_logs/sfd_client_spec_11c.log ../spec_logs/sfd_client_spec_modified_11c.log
matchlog ucl_client_11b.log ../spec_logs/sfd_client_spec_11b.log ../spec_logs/sfd_client_spec_modified_11b.log
matchlog ucl_client_11a.log ../spec_logs/sfd_client_spec_11a.log ../spec_logs/sfd_client_spec_modified_11a.log
matchlog ucl_client_10c.log ../spec_logs/sfd_client_spec_10c.log ../spec_logs/sfd_client_spec_modified_10c.log
matchlog ucl_client_10b.log ../spec_logs/sfd_client_spec_10b.log ../spec_logs/sfd_client_spec_modified_10b.log
matchlog ucl_client_10a.log ../spec_logs/sfd_client_spec_10a.log ../spec_logs/sfd_client_spec_modified_10a.log
matchlog ucl_client_09c.log ../spec_logs/sfd_client_spec_09c.log ../spec_logs/sfd_client_spec_modified_09c.log
matchlog ucl_client_09b.log ../spec_logs/sfd_client_spec_09b.log ../spec_logs/sfd_client_spec_modified_09b.log
matchlog ucl_client_09a.log ../spec_logs/sfd_client_spec_09a.log ../spec_logs/sfd_client_spec_modified_09a.log
matchlog ucl_client_14c.log ../spec_logs/sfd_client_spec_14c.log ../spec_logs/sfd_client_spec_modified_14c.log
matchlog ucl_client_14b.log ../spec_logs/sfd_client_spec_14b.log ../spec_logs/sfd_client_spec_modified_14b.log
matchlog ucl_client_14a.log ../spec_logs/sfd_client_spec_14a.log ../spec_logs/sfd_client_spec_modified_14a.log
matchlog ucl_client_07c.log ../spec_logs/sfd_client_spec_07c.log ../spec_logs/sfd_client_spec_modified_07c.log
matchlog ucl_client_07b.log ../spec_logs/sfd_client_spec_07b.log ../spec_logs/sfd_client_spec_modified_07b.log
matchlog ucl_client_07a.log ../spec_logs/sfd_client_spec_07a.log ../spec_logs/sfd_client_spec_modified_07a.log
matchlog ucl_client_06c.log ../spec_logs/sfd_client_spec_06c.log ../spec_logs/sfd_client_spec_modified_06c.log
matchlog ucl_client_06b.log ../spec_logs/sfd_client_spec_06b.log ../spec_logs/sfd_client_spec_modified_06b.log
matchlog ucl_client_06a.log ../spec_logs/sfd_client_spec_06a.log ../spec_logs/sfd_client_spec_modified_06a.log
matchlog ucl_client_05c.log ../spec_logs/sfd_client_spec_05c.log ../spec_logs/sfd_client_spec_modified_05c.log
matchlog ucl_client_05b.log ../spec_logs/sfd_client_spec_05b.log ../spec_logs/sfd_client_spec_modified_05b.log
matchlog ucl_client_05a.log ../spec_logs/sfd_client_spec_05a.log ../spec_logs/sfd_client_spec_modified_05a.log
matchlog ucl_client_04c.log ../spec_logs/sfd_client_spec_04c.log ../spec_logs/sfd_client_spec_modified_04c.log
matchlog ucl_client_04b.log ../spec_logs/sfd_client_spec_04b.log ../spec_logs/sfd_client_spec_modified_04b.log
matchlog ucl_client_04a.log ../spec_logs/sfd_client_spec_04a.log ../spec_logs/sfd_client_spec_modified_04a.log
matchlog ucl_client_03c.log ../spec_logs/sfd_client_spec_03c.log ../spec_logs/sfd_client_spec_modified_03c.log
matchlog ucl_client_03b.log ../spec_logs/sfd_client_spec_03b.log ../spec_logs/sfd_client_spec_modified_03b.log
matchlog ucl_client_03a.log ../spec_logs/sfd_client_spec_03a.log ../spec_logs/sfd_client_spec_modified_03a.log
matchlog ucl_client_02c.log ../spec_logs/sfd_client_spec_02c.log ../spec_logs/sfd_client_spec_modified_02c.log
matchlog ucl_client_02b.log ../spec_logs/sfd_client_spec_02b.log ../spec_logs/sfd_client_spec_modified_02b.log
matchlog ucl_client_02a.log ../spec_logs/sfd_client_spec_02a.log ../spec_logs/sfd_client_spec_modified_02a.log
matchlog ucl_client_13c.log ../spec_logs/sfd_client_spec_13c.log ../spec_logs/sfd_client_spec_modified_13c.log
matchlog ucl_client_13b.log ../spec_logs/sfd_client_spec_13b.log ../spec_logs/sfd_client_spec_modified_13b.log
matchlog ucl_client_13a.log ../spec_logs/sfd_client_spec_13a.log ../spec_logs/sfd_client_spec_modified_13a.log
